# Etapa de construcción
FROM maven:3.8.5-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package 

# Etapa de ejecución
FROM openjdk:17-jdk
LABEL author=marcelobatista.dev
WORKDIR /app
COPY --from=build /app/target/helpingPets-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]