version: '3'

services:
  app_helping_pets:
    env_file:
      - .env
    build: .
    ports:
      - "8082:8080"
    environment:
      DATABASE_URL: jdbc:mysql://helping_pets_db:${DATABASE_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=FALSE
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    depends_on:
      helping_pets_db:
        condition: service_healthy
  helping_pets_db:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10